### ISSUE TITLE
Image URL not recognized as image 

### ISSUE THREAD

**Issue by TommySlokky** [BerndGabriel/HtmlViewer#212]
If you have code like this:
`<a href="http://sourceforge.net"><img src="http://sflogo.sourceforge.net/sflogo.php?group_id=92177&amp;type=1" alt="" width="88" height="31" /></a>`

HtmlViewer will not recognize it as an image in 

ThtImageLoader.LoadImageFromStream where it calls KindOfImage

I can see the code is not happy about the header inside the stream graphic content... I don't know - maybe one could use MIME detection as fallback or similar

**Comment by BerndGabriel** [comment]
I cannot reproduce this issue, but there are some prerequisites to load resources from sources other than your (local) file system:
1) Use TFrameBrowser
2) Use ICS or Indy Components to load data (see FBrDemUnit.pas for details)
3) In Delphi before 2009 you must not define NoGDIPlus, which is used to show the PNG-file.

Okay, maybe I got it: since Delphi 2009 there is unit PngImage to handle PNG-Files, but LoadPng() does not use it.

**Comment by BerndGabriel** [comment]
https://github.com/BerndGabriel/HtmlViewer/commit/5f2fea8584cc88a4f7523c0c423db022fab62349 adds PNG file handling without GDIplus for Delphi >= 2009. Printing transparent areas fails without GDIplus.
