### ISSUE TITLE
Please add LoadFromResourceName

### ISSUE THREAD

**Issue by OLLI-S** [BerndGabriel/HtmlViewer#257]
It would be very cool if you add the method **LoadFromResourceName**.
This way I can go to the Project Options -> Resources and add my HTML resources (multiple) in the project.
Then I load the resource with a single line of code:
`MyHtmlViewer.LoadFromResourceName(HInstance,'NAME_OF_RESOURCE'); `

**Comment by kqha** [comment]
I think it's quite simple though to load the HTML *only*, the real problem is the handling for the HTML resources (e.g: images). Unless you want to write custom handlers (which is not that different than writing the HTML handler), should do the job.

For example:
```
procedure loadHTMLFromStream(resname : string);
var
  res : TResourceStream ;
begin
  res := TResourceStream.Create(HInstance,resname,RT_RCDATA);
  strm.CopyFrom(res,res.Size);
  strm.Position := 0;
  MyHTMLViewer.LoadFromStream(strm);
  strm.Free;
end;
```
By adding some ifs in OnImageRequest, OnSoundRequest,... can give you suitable handler for the HTML resources

**Comment by BerndGabriel** [comment]
Handling resources is implemented within HtmlViewer.pas resp. HtmlSubs.pas.
