### ISSUE TITLE
Problem installing on Delphi 10.1

### ISSUE THREAD

**Issue by svenson8** [BerndGabriel/HtmlViewer#339]
Hello,
I have problem with compiling FrameViewer.dpk on Dlephi Berlin 10.1.
When I open file /Rad Studio 10.1/FrameViewer.dpk Firstly I get Class TBegaZoomBox not found. After I ignore it while compiling I get 
"HtmlPrinter not found", so I added it to project. Then file dpk is little corrupet like "r" is added to rrequiierd 
After repairing dpk I get IntoHex function compiling problem...

**Comment by BerndGabriel** [comment]
TBegaZoomBox is registered by dclFrameViewer.dpk. You should abort loading the form as long as it misses controls. Otherwise you damage the unit.

Commit https://github.com/BerndGabriel/HtmlViewer/commit/743f5a6d4bcb574ff6852ca3a233962e2106788f adds the missing unit to frameviewer.dpk in the master branch.
